### ISSUE TITLE
DoD Summary Properties Settings

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#171]
@philipbaileynar The option to scale the x-axis for the DoD Histogram is currently greyed-out while the y-axis scaling appears to work. see:

![image](https://user-images.githubusercontent.com/35811609/37381056-1e55cef2-27a0-11e8-939f-67615bf09d12.png)

**Comment by philipbaileynar** [comment]
See my 5th March comment on #136 where I note that my attempts to override the x axis scale failed because that axis is categorical. It should be possible, but it will take time to investigate. I've disabled the controls for the x axis until I get this working.

Note the rest of the comments on #136 where @joewheaton points out that we actually need to set the y axis scale for all the different charts. The current implementation is floored because the manual value is set only for the histogram, but affects both area and volume charts, which is not useful.

**Comment by jb10016** [comment]
Apologies for missing that!
