### ISSUE TITLE
Naming Conventions?

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#187]
@philipbaileynar - so a quickie ... it seems that when you repeat a change detection with the same two surfaces and keep everything constant EXCEPT the choice of 'area of interest' ... the resulting names of the two change detections are indentical ... albeit that the second change is appended with (1).  Clearly there is no ambiguity here ...  the two change models are distinct and have defined names ... the problem is you cannot distinguish this from the automatic name.  

I suspect the clearest way around this is to encourage users to edit the names themselves ... but is there any scope to change this by default or perhaps better still, an option to edit the change detection name in the same way you can update the properties of a DEM survey?

**Comment by philipbaileynar** [comment]
Agreed. Let's make the DoD name editable on the results form:

![2018-03-21_202924](https://user-images.githubusercontent.com/8645379/37749744-b13bd580-2d46-11e8-8108-826fea7d483d.png)

I don't want to increase the complexity of naming the DoDs by including the name of the extent (AOI or otherwise). It's already a bit of a mouthful with just the two surfaces and the uncertainty method.

**Comment by jb10016** [comment]
Yes - this sounds like a sensible move to me.  I do wonder also whether we should allow for deletion of specific change detections, just as we do for DEM surveys/masks etc.  The batch processing - while great - risks creating large, unnavigable project trees that probably contain lots of unwanted material.  I know Joe's view was to enable the user to highlight key results rather than ditch others, but I'd be interested to hear your thoughts ...

**Comment by joewheaton** [comment]
I think we should:

   1. Do as Phlip suggests and make change detection name editable.
   2. Do as James suggests and make change detections deleteablle.
   3. And Update automatic naming so that it differentiates:
   1. CDs based on AOIs
      2. CDs with Bayesian Updating

Good suggestions James.


_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org
