### ISSUE TITLE
Morpholocal Cumulative and Net Graphs on BS

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#194]
Add the morphological charts to the budget segregation results screen (when the BS is run from a directional mask only). The Volume out chart is replaced by a cumulative vol change and a net vole change chart.

Line for cumulative. Bars for net.

![2018-03-28_141352](https://user-images.githubusercontent.com/8645379/38056797-59bd1354-3292-11e8-886e-eec93fb18110.png)

![2018-05-08_165006](https://user-images.githubusercontent.com/9723905/39786927-ff231eac-52df-11e8-959d-4943d33bd494.png)

**Comment by joewheaton** [comment]
This is @jb10016 top 4 a list priority (3 of 4).

**Comment by philipbaileynar** [comment]
@jb10016 and @joewheaton I have refactored the chart from the morphological results to now also appear on the budget seg results. See below. I think the top graph is the same for both uses and I have this working. However, I have some questions about the lower graph:

1. Should the lower graph be a line or bars on the BS results? My take is that it should be bars for directional masks that don't have a distance field, but a line when the mask does have a distance field? (Please ignore the lower graph X axis until this question is answered).
1. There's no uncertainty whiskers for the bs results view, correct?
1. What should I call the tab on which the chart appears in the BS results? It's currently "All Categories" but this is kinda lame.

![2018-07-30_152555](https://user-images.githubusercontent.com/8645379/43427143-2b730242-940d-11e8-88ed-a119cac9f355.png)

**Comment by jb10016** [comment]
@philipbaileynar @joewheaton Hi Guys - thanks for this Philip - I think this is an important addition.  In terms of your questions then:

1.  Your suggestion re lines/bars makes sense given the continuous nature of distance based data (although to do so, we probably need to be clearer regarding what the distance actually means in this context - is it for example, the centroid of the budget cell?).  

However, I am still a little unsure whether lines is the best visualization tool.  The volumes plotted in these graphs are integrated from discrete spatial units, and may therefore contain a bias resulting from the different area of each polygon that could be obscured by plotting as a continuous function.  Using average depths (m3/m2) gets around that, but ultimately people are likely to want to know the actual vols in each cell I suspect.   

Overall, I think I would therefore stick to presenting both graphs here as bar charts - the issue is whether the x-axis needs to be scaled to account for irregular linear sampling when distance is available.  That would make sense, but then you run in to the question of whether the bars should be scaled too, or the widths remain constant (probably my preference).

Beyond, these points, I am a little less sure why you suggest this issue only pertains to the lower graph? I wonder - is this because you are thinking this should be the cumulative vol - as is shown (but incidentally not labelled as such in the morpho plot)?  For the BS results however, I think the key graph here is simple the net change - which again should plot sensibly as a bar?  

2.  Following the logic of my final point above (i.e., the lower graph is net change not cumulative) then both plots should have whiskers no?

3.  Naming ... I guess we run into an issue here, in that we only want this tab to become available for BSs created with a directional mask?  If it is possible to effect this (perhaps my greying out or omiting the tab for regular BSs) - perhaps it would then make sense to label this tab as 'Longitudinal Breakdown', while the pie charts could be called 'Volumetric Breakdown' or 'Statistical Breakdown' or even more simply 'Pie Charts'?!

I'm not sure how much sense the above makes ... I'm still reeling from the lack of sleep since our little lady was born the week before last!  ;-)

**Comment by philipbaileynar** [comment]
@jb10016 Congrats! And the chaos returns!

1. Always having the bottom chart as bars, regardless of the purpose actually makes things a lot easier! 
1. Your concerns over the distance value to use and bar widths etc is extremely valid. Let's not go there. The bar widths and spacing will be constant.
1. Yes, the chart in question is **only** displayed for directional BS. The tab is not visible for non-directional BS. I like "Longitudinal Breakdown" and "Pie Charts".

**Comment by jb10016** [comment]
@philipbaileynar Chaos is certainly the word ... ;-)

All sounds good to me, though be interested to hear the thoughs of @joewheaton 

Just a thought ... how hard would it be to offer the option to export the data behind the graph (rather like the CSViewer does)? Or perhaps easier ... link a button here to take them directly to the intercomparison spreadsheet that documents the data (but actually doesn't contain the distance field)?

**Comment by philipbaileynar** [comment]
@jb10016  and @joewheaton here's the latest implemention. Please review and provide feedback. There are some questions in the video:

https://youtu.be/sHPhpEsUMp8

**Comment by jb10016** [comment]
Nice work @philipbaileynar .. a little feedback:

a) For the longitudinal breakdown I like the idea of using the same red/blue colour scheme on the net change graph and wondered whether the way of avoiding titles and the legend would be to change the y-axis titles, i.e., top graph = volumes of +ve/-ve vertical change (m); and lower graph = net vertical change (m).  Happy to hear alternatives ... but this neutral language gets around the current legend labels (erosion/deposition) and means that both graphs are self-explantory.

b) sorting the spacing of the lower graph to match the top would be excellent if possible.

c) like the pie-chart title - seems clearer to me, though is there anything we can do as a quick fix on that set of graphs to reposition the titles which currently overlap the chart?

d) I think the option to genericize (boy what an awful Americanism ...) the longitudinal breakdown is a good idea and would enable a quick overview of the pattern of changes by polygons for a regular BS.  The problem - as you suggest - is would this become illegible when you have 10+ segments to present, especially given the need to see the x-axis label to make sense of it?  

I wonder if a potential work-around could be to add in some hovertext that reveals the name of the category when you place your mouse over bar?  Incidentally, that would work well for the pie charts too ....

**Comment by philipbaileynar** [comment]
Issue implemented. closing.
