### ISSUE TITLE
When deleting a change detection, refresh tree

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#221]
## The Problem

If you have a single change detection in a pairwise folder in tree, and you delete the change detection (it does this correctly), but it keeps (initially) the parent folder in project explorer tree. Here is the view before deleting:
![before_delete](https://user-images.githubusercontent.com/9723905/38863284-5c7f6b20-41f4-11e8-9c46-a7b43ff08a02.png)

And after:
![after_delete](https://user-images.githubusercontent.com/9723905/38863311-6dec5d8c-41f4-11e8-9f92-198af186b77a.png)

You can get around this 'problem' by refreshing the tree. However, we might just want to refresh for the user so they don't get confused.

**Comment by joewheaton** [comment]
This appears to be fixed. Quick test:
https://youtu.be/nOb35Jtt8pI

**Comment by joewheaton** [comment]
I spoke too soon. There are some collisions that come up when working in both GCD StandAlone and AddIn simultaneously. I haven't broken all these out into separate bugs. I'll let you @MattReimer  do that. See:  https://youtu.be/7d6RnMWcso0?t=45s onwards.

**Comment by MattReimer** [comment]
@joewheaton I watched the video and I'm a little fuzzy as to what actually happened. 

In general though I think we're going to have to choose our battles here. We really can only support a very narrow workflow with respect to running both apps.

The GCD saves a project by dumping everything it has in its memory to a project file. It doesn't do a read first to see if anything has changed... because that would be brutal to handle (we'd have to invent a collision handling system and make 100+ little decisions about what to do if something is different).
 
I think the hard and fast rule is: **if you "do" anything in either the Standalone or the Addin you need to refresh the project in the other one before you "do" anything else.** 

So if you find anything that violates this rule then I think we have something to try and fix. Otherwise I don't really see any way to fix it.

**Comment by MattReimer** [comment]
I agree this may be more of a documentation piece than anything.

A further bullet point you may want to add to this:

* Choose one (either Standalone or Addin) as the "Doer" and one as the "Watcher". If you "Do" in both then you break the warranty.

The integrity checking is a big piece that is currently unwritten (we can't re-use any piece of what we had in 6) so it's going to have to be a future feature.
