### ISSUE TITLE
Legacy Project Opening bug

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#226]
Joe wasn't able to open a project he made with a really recent version of GCD (I think it was 7.0.14)

The issue has to do with deserializing the error of a DoD ([line 58 of DoDPropagated.cs](https://github.com/Riverscapes/gcd/blob/902f3f3e5a07d68d33edeb8d8e02c5fbe50f7ccf/GCDCore/Project/DoDPropagated.cs#L58))

Specifically:

```csharp
ErrorSurfaces.First<ErrorSurface>(x => string.Compare(errorName, x.Name, true) == 0);
```

The project is really large so I won't pack it up here but I'll give you the project file and relevant lines
[`x-> name` is coming in as "Error"](https://gist.github.com/MattReimer/e4151e8e9c4f52f97619601368608095#file-orc_test-gcd-xml-L21)

but `errorName` [is coming in as "Uniform"](https://gist.github.com/MattReimer/e4151e8e9c4f52f97619601368608095#file-orc_test-gcd-xml-L719)

So, as a result this will never find anything

Let me know if this isn't enough to go on.

**Comment by philipbaileynar** [comment]
I'm unable to reproduce this.

As @MattReimer suggests, the problem is that one of the DoDs refers to an error surface that doesn't exist in the project. I thought that this might occur in one of two ways:

1. After generating the DoD, the user goes back and renames the error surface. I tried this, but the GCD is correctly updating both the error surface name as well as the name of the error surface that the DoD refers to.
1. User deletes the error surface referenced by the DoD and then adds another one with a different name. I tried this but got the warning that the error surface is in use and cannot be deleted.

@joewheaton do you recall your workflow or what you did just before the error occured and you were unable to load the project? I suspect something got renamed somewhere and a reference wasn't updated.
