### ISSUE TITLE
Improvements to Budget Segregation Form

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#230]
## The Context
We've gone to great lengths to have a really nice mask library that separates out Masks into three types:
1. Regular Masks
2. Directional Masks
3. AOIs
![3masktypes](https://user-images.githubusercontent.com/9723905/38885523-7ab9cb08-4230-11e8-9591-c9370301ce0b.png)

## The Problems & Suggested Enhancements
However, when we get down to budget segregation, we are just using one legacy form we inherited from before to do everything and its really confusing to the user. This starts with the right-click context to do a budget seg:
![splitout](https://user-images.githubusercontent.com/9723905/38885771-517e195a-4231-11e8-9aaa-baedebf1c6e1.png)

We should either:
- Add a choice on context menu to at that stage choose whether to do a budget segregation with a regular mask or directional mask.
- OR add a selection within the BS form (radio button) for whether you want to do a BS based on Directional or Regular Masks. Radio would be default.
In either case, the masks you choose from in pull down should be filtered to JUST those mask types. Once you're in the form, this form inherits way too much from the old form that is just confusing context. We don't need any of the crap on the Change Detection from which this came (either hide it in collapsible control or get rid of it). The user already knows what change detection this is for as they had to naigate through the explorer tree to get here. It distracts the user from the only two things they really need to specify in this form. Specifically:
1. What Mask to load from mask library (please change label from `Feature Class` to `Mask`)
2. What name to give this BS
![changesbs](https://user-images.githubusercontent.com/9723905/38885893-9bcc65de-4231-11e8-9f23-8e194bf2169a.png)
We SHOULD NOT show them the `Field`, it confuses user that they have a choice. That choice was inherited back at mask stage. If ANYTHING, we might want to change Auto-Naming in Mask Library to have:
- A prefix based on mask type (e.g. `dir_` for directional `msk_` for normal and `AOI_` for area of interest
- A core based on shapefile name
- A suffix `_field` based on the field they chose for regular mask and nothing for others?

I think this would keep things less confusing.

Finally, it is confusing that All Budget Segregation nodes have same symbol (i.e. pie chart). They could/should differentiate based on whether Directional or Regular. Moreover its confusing that the right click `Add Morphological Analysis` shows up for all budget segregations. 
![morphan](https://user-images.githubusercontent.com/9723905/38886371-fd5a298e-4232-11e8-90f9-90d42bcabd56.png)
This is of course is met with this error message when I attempt it for a Regular Mask:
![inalid](https://user-images.githubusercontent.com/9723905/38886370-fd54d4de-4232-11e8-8d5c-16f042a1e21c.png)

While technically correct, it makes more sense (if we do above) to only have option in right click context menu on a Budget Segregation to do it if it is derived from a mask of type Directional.

**Comment by philipbaileynar** [comment]
Updated implementation...

(Note my personal design philosophy that menu options, buttons and other UI controls should only ever be disabled and never hidden. It's hard to learn a piece of software if some items are not always visible, whereas a greyed out item is a visual cue that something is possible but perhaps not appropriate for the current configuration.)

I don't like the split context menu shown above and prefer distinguishing the mask types on the form itself. See following screenshot. I've worked hard to make this easy to use so that if there are no regular masks in the project but there are directional masks, then default switches to directional etc.

![2018-05-03_132041](https://user-images.githubusercontent.com/8645379/39600883-f81b4062-4ed4-11e8-8fb3-57ac68b24595.png)

I've also disabled the context menu for Morphological analysis when the user right clicks on a budget seg that uses a regular mask. i.e. this option is only available for directional masks.

![2018-05-03_132307](https://user-images.githubusercontent.com/8645379/39600959-41c45820-4ed5-11e8-9033-e34051232383.png)

**Comment by joewheaton** [comment]
Nice one.

**Comment by joewheaton** [comment]
This is working really nice now. This tested well:
https://youtu.be/hzepiR2XjKw

Two minor requests (feel free to assign this to Future Requests milestone):
1. Change symbol for directional Budget Segregation in Tree to: 
![maskdirectional_icon](https://user-images.githubusercontent.com/9723905/39786850-b2473b7c-52df-11e8-902c-2254894734ef.png) Maybe with Blue and Red fill or something....
2. Sort the list in the Budget Seg form for directional mask by the Typology (just like you do in subsequent morphological analysis.
And a reminder of James request to add to the directional mask (#194)
![2018-05-08_165006](https://user-images.githubusercontent.com/9723905/39786927-ff231eac-52df-11e8-959d-4943d33bd494.png)

**Comment by MattReimer** [comment]
Refiled as #279 and #280
