### ISSUE TITLE
GCD 6 reference in Help menu

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#238]
AddIn Only. Look in the help menu. There's a referene to "GCD 6". Should be 7

Really small item.

**Comment by joewheaton** [comment]
I'm still seeing this issue in the AddIn for 7.0.16.  Is this because you did fix it, but we have not had a pre-release since then? If so close this issue again....
![helpmenu](https://user-images.githubusercontent.com/9723905/39659057-391eea6a-4fdd-11e8-924b-68ad226d6430.png)

![helpmenubug](https://user-images.githubusercontent.com/9723905/39659056-2ea5b262-4fdd-11e8-9bd2-eac36058eb3a.png)
See also #268

**Comment by MattReimer** [comment]
You're right @joewheaton . This will appear in the next version. Re-open it if not.
