### ISSUE TITLE
Reset default colors button

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#244]
WE should have one so we can get back the default colors if we change them

**Comment by joewheaton** [comment]
In the `Customize` -> `GCD Options` command under the 'Graphs' tab. Because the only way to exit this is to `Close`, so if you change things and change your mind you're in trouble. No cancel available. Plus, it would be nice to get back to defaults. 

![graphoptions](https://user-images.githubusercontent.com/9723905/38935087-a20ec4a6-42da-11e8-8e76-6062599c724b.png)

**Comment by philipbaileynar** [comment]
![2018-05-03_093334](https://user-images.githubusercontent.com/8645379/39590198-113ad8d4-4eb5-11e8-8eb4-c96e9f2639c7.png)

**Comment by joewheaton** [comment]
I was testing on #253, and I discovered that while the refresh to defaults works, the actual use of these default colors in graphs is NOT working. You can update them in viewing an individual change detection result and that works nice. However, changing the default colors does not seem to have an impact on the change direction results:
https://youtu.be/o57fkaZK9o0

**Comment by philipbaileynar** [comment]
Yeah, so I think this is straightforward to fix, but the workflows are a little convoluted...

Right now I think that the only time that the software setting colors are read is at GCD launch. So you get to change the software setting colors in the options form but they don't actually get used! Doh. 

The fix is simple. When the user changes the software setting colors in the options form they not only need to get written to the software settings (for the next session) but they also need to get written to the [variables stored on the Project manager singleton](https://github.com/Riverscapes/gcd/blob/master/GCDCore/Project/ProjectManager.cs#L26-L27). This is a 2 second fix.
