### ISSUE TITLE
Renaming a DoD not reflected in map legend

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#249]
When you rename a Dod and add it back to the map, the map still uses the old name.

Steps:

1. Create Dod. (auto added to map)
2. Rename the Dod.
3. Remove the old DoD from the map.
4. add the renamed Dod to the map and notice the name in the ArcMap legend is wrong.

**Comment by philipbaileynar** [comment]
This is related to item #192.

Fundamentally it comes down to the fact that state is being stored in 2 places. The fix is actually not that hard, but somewhat pervasive.

Some (but not all) collections of objects (DEMs, DoDs etc) are stored in the project object model as dictionaries instead of lists. These dictionaries use the object name ("My Cool DEM") as both the dictionary key as well as the object Name property. Renaming items requires that the name string is changed in both places and obviously this is being handled inconsistently (again, see #192). Dictionaries were chosen originally because the concept of keys ensures uniqueness.

The fix is to switch these collections from dictionaries to lists. This does involve some work and makes a few tasks harder (ensuring unique names is easy when its just checking a dictionary key) but also makes some tasks easier (list collections can be bound directly to controls, whereas dictionaries need and extra two steps to obtain the dictionary values as a list).

I am happy to convert the few remaining dictionary collections to lists. I contemplated doing this before the Scotland workshop, but held off because it does have the potential to temporarily destabilize the software.
