### ISSUE TITLE
Need to review upstream and downstream dependencies related to file deleting... 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#260]
## The Problem
We should take a pass through everything in the project file and project explorer and make sure that what we allow deleting based on what inputs and intermediates it was based on is enforced correctly. I have not found any problems yet per se, but we should double check its doing what we expect. What we expect is:
1. If user attempts to delete any node in project explorer, they are not allowed to delete it if there is a downstream dependency (e.g. if I delete a DEM Survey, that is used in DoD analyses in the project, the user should be blocked from doing so.
2. If user attempts to delete any node in project explorer that has an upstream dependency (i.e. it has child items), we warn them that there are children (e.g. delete DEM Survey, but it has child associated surfaces and error models)  and ask them if they are sure they want to delete those too. 

I guess we should just flesh out what we expect to happen where and confirm it is happening.

We could make life easier for the user and in the warning point them to the list of dependencies we are finding.

**Comment by philipbaileynar** [comment]
All GCD project items has an "IsItemInUse" flag that should be correctly flagging if an item can or cannot be deleted. Some of the dependencies can get pretty nested, but I think I have all the checks correct. The current warnings are indeed somewhat vague "item is in use". The warnings don't list all the dependencies because this list can get long if you've performed batch DoDs etc.

**Comment by MattReimer** [comment]
We're pretty confident this issue is resolved and that all the code for performing deletions is centralized. I'm going to close this issue and then let's re-open it for a specific problem with repro steps.
