### ISSUE TITLE
Sort Budget Seg form for directional mask

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#280]
Sort the list in the Budget Seg form for directional mask by the Typology (just like you do in subsequent morphological analysis.

 
Related to last comment in #227

**Comment by philipbaileynar** [comment]
@joewheaton I think we have found a fundamental floor in the was GCD hands masks... Imagine the following polygons organized from upstream to downsteam. The number represents the topological direction value and the text is the field value:

1. alpha
2. beta
3. charlie
4. alpha
5. beta

The budget segregation results dropdown for this mask - even though its a directional mask - would be:

* alpha
* beta
* charlie

Should you proceed to perform a morphological analysis on this budget segregation what should the topological order be for alpha and beta? There are multiples of both.

For this to work we need to enforce unque field values (and labels if you choose to use them) so that the budget segregation does not merge polygons together. **Is this a reasonable constraint?**

**Comment by joewheaton** [comment]
## Initial response
Excellent question @philipbaileynar. I had not actually considered this very real possibility. While what you're proposing is a reasonable constraint... - i.e.
 
> For this to work we need to enforce unique field values (and labels if you choose to use them) so that the budget segregation does not merge polygons together.

... I don't like it. I think the reason I don't like it, is it sounds like a bunch of work either to check to enforce this of user, or to explain to user.  I actually did realize this the other day when I was checking this functionality in #227... you see me stumble across this in https://youtu.be/cf267NYqYlI?t=3m37s.

### The Basic Problem
As a legacy for how we've always done budget segregation, we've always thought of this as a 'categorical' masking problem and your example above illustrates nicely how we've always *required* a text field to play ball (in example above, the text field has three unique categories: alpha, beta and charlie). This all makes sense for a Regular Mask and I don't propose we change any of that for that. However, our problem comes in directional masks! The requisite that matters here is NOT the text field, its the unique integer topology field! So, its 1, 2, 3, 4... n that matters, not alpha, beta, charlie, alpha, beta. 

## A More Logical Way Forward
The most logical way forward is to ONLY require the Topological 'Direction Field' when adding a directional mask to the library. This would then make the text field (previously labeled 'field') obsolete. You then make the **text** 'Label' field optional too, and if repeats, you don't care, because that's how you're labeling it. 

![2018-05-14_013126](https://user-images.githubusercontent.com/9723905/39984088-3c800e6e-5717-11e8-8c85-6f9ad26b3835.png)

What you do by default is when performing a budget segregation, you DO what we want, which is the 'Budget Class' pull down in the BS Results should now refer just to the integer 'Direction' field, but if a 'label' is provided, you could just display that in pull down list (don't worry about if it repeats). So in your example, we have two scenarios:
1. If the user did not specify an optional 'text label' field, the Budget Class pull-down categories are: 1, 2, 3, 4, 5
2. If the user did specify an optional 'text label field, the Budget Class pull-down categories are: apha, beta ,charlie, alpha, beta

## Is XML already set up for this??? Or does it need rethinking?
I found interesting that in the project XML (see #279), that suggests that the logic I propose above is what you're already doing anyway (i.e. you don't bother to record in the mask library in the case of directional masks any `<items>` or budget classes as you know it's a waste!

**Comment by philipbaileynar** [comment]
Closing this issue because we have now handled sorting for directional masks (#235). Non-directional masks have no inherent order.
