### ISSUE TITLE
Vector-Raster calculations

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#290]
@MattReimer just a quickie - I'm wondering how grid-in-polygon intersections are now processed in GCD 7.  Specifically thinking here about masks/AoIs etc.  

Where a vector splits a gridcell, how is the cell attribute allocated to polygons?  Is the contribution interpolated and split between polygons, or attributed on a max area basis?

Cheers,
James

**Comment by MattReimer** [comment]
Hi James (@jb10016 )

Maybe I'm not reading this correctly but I don't think we ever go from raster to vector so that kind of interpolation doesn't really ever come up. 

For masks and AOIs we're converting from vector to raster and do it by looking for the center of the cell and then checking if that one point intersects a polygon.

One effect of this is that overlapping polygons can create strange effects. Since a raster cell can only have a single value it takes the first one it finds which may not be the one you intend. 

We originally had GCD working with overlapping vectors but you might recall we had some pretty severe performance problems so we made the decision to cut this support.

Let me know if this doesn't help.

**Comment by jb10016** [comment]
@MattReimer Hi Matt - I think it's just my rather quick and confusing note that caused the confusion.  Essentially, I was asking about the sampling of rasters by our vector masks as you deduced.  So, I take from your response that cells attributes (i.e., volumes of raising/lowering) are allocated to features in a mask (i.e., a BS) based on the intersection of the cell centre and the vector feature?  So there is no attempt to interpolate across cells (i.e., weighted allocation to two polygons) but also no cells can be counted twice.  Does that make sense?!

**Comment by MattReimer** [comment]
Yes @jb10016 . You got it. Exactly!

**Comment by jb10016** [comment]
Thanks @MattReimer !
