### ISSUE TITLE
Cross Section Viewer Scrolling Bug

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#298]
@philipbaileynar Hi Philip,

As promised a link to a quick [video ](https://drive.google.com/open?id=1UgeJV_d_eYUd0GvsgmhjfoAXA9Gv7bfo).  This is based on the same project I've recently shared incorporating just one DEM and one route.

**Comment by philipbaileynar** [comment]
Great video @jb10016 Thanks!

@MattReimer I now think that the problem is that the two open forms (basic cross section plot and surface difference plot) are sharing the same list of cross sections and they are fighting to control the selected cross section. This should be a simple solution of cloning the lists (but not the underlying Cross Section objects that the list contains) thereby decoupling the selection. 

I will test and fix tomorrow.

**Comment by jb10016** [comment]
@philipbaileynar @MattReimer  Great to hear you think you understand the provenance of this one.  Sounds like a good explanation and hopefully and easy fix too :-) Thanks!

**Comment by philipbaileynar** [comment]
@jb10016 this should be fixed in [2.0.10 release](http://xsviewer.northarrowresearch.com/release_notes.html) put out this morning.

**Comment by jb10016** [comment]
@philipbaileynar Thanks Philip - seems to be working well now.
