### ISSUE TITLE
Changes to Change Detection Form

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#33]
@philipbaileynar,
@jb10016 and I were looking at some minor tweaks to the change detection form that would improve this for pedagogy and user-education.  Also we update some defaults. Check [this video out](https://youtu.be/kH8YepgpWKQ).

[GenericChangeDetection Form.pdf](https://github.com/Riverscapes/gcd/files/1670798/GenericChangeDetection.Form.pdf)

**Comment by philipbaileynar** [comment]
@joewheaton I want to keep the the change detection form as simple as possible and would prefer not to introduce new controls if we can help it.

Rather than the proposed new radio buttons how about simply loading both the DEMs **and** the reference surfaces into the **old** dropdown control. So the changes to the form would look like below. Note that the selection of new and old rasters for the purposes of change detection is a user control that is reused on both the single DoD and the multiple uncertainty DoD form.

![2018-02-07_153505](https://user-images.githubusercontent.com/8645379/35947399-960876c4-0c1c-11e8-83e7-34954bdd76d2.png)

**Comment by philipbaileynar** [comment]
Closing #45 because it's a duplicate:

This is done. Need to get approval from others whether they like my solution:

![2018-02-09_110727](https://user-images.githubusercontent.com/8645379/36045410-78fa64e2-0d8a-11e8-9d0b-a12069d8a5da.png)

**Comment by philipbaileynar** [comment]
@joewheaton can you please review your original requirements for this ticket and close if you're seeing everything accomplished in the GCD progress videos.

**Comment by philipbaileynar** [comment]
Closing this form because all the changes should be implemented with the exception of the probabilistic/confidence interval controls which should be captured in issue #37
