### ISSUE TITLE
Problem adding Dems to GCD

### ISSUE THREAD

**Issue by nicole-4** [Riverscapes/gcd#336]
When going to "Add existing DEM survey", an error pops up and it fails to add the DEM.

This is the following error message:

```
Object reference not set to an instance of an object.
 --- Stacktrace --- 
   at GCDCore.UserInterface.SurveyLibrary.GISDatasetValidation.DSHasSpatialRef(GISDataset gisDS, String sTypeSingle, String sTypePlural)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PrepareToImportRaster(Surface refSurface, Purposes purpose, String Noun, IntPtr parentWindow)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.6.0.8321
GCD = 7.4.0.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 23/12/2018 10:49:27 AM
```
Can someone please help me? I've tried making sure that my DEMs are dimensionally divisible.

**Comment by philipbaileynar** [comment]
Hi @nicole-4 is this still an issue?

1. Can you describe the precise steps right before the error occurs? 
    1. Does the window for selecting a raster layer open?
    1. Do you actually get to click on a raster layer before the error happens?
1. Better yet can you record a video and then upload to YouTube so that we can see the problem in action.
1. Are your rasters file-based (*.tif or *.img) or are they in a geodatabase?
1. If it's a particular raster that's causing problems can you zip it up and send it to me please? Or even zip up your whole GCD project (the folder containing the *.gcd file) and send that.

**Comment by nicole-4** [comment]
Hi there,


Thanks for getting back to me but I managed to solve the issue. I hadn't
saved the rasters with the .tif extension.


Many thanks,
Nicole
