### ISSUE TITLE
Reference Surface UI

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#51]
Implement the reference surface user interface.

* Adding DEM reference surfaces
* Adding constant reference surfaces
* Adding error surfaces for reference surfaces

**Comment by jb10016** [comment]
@philipbaileynar @MattReimer @joewheaton 

Again, this looks neat and tidy.  

I do like the additional idea of specifying (deriving I guess) an error surface on addition or creation of each surface.  This raises some interesting questions however:

1) if it's a case of simple single reference (or indeed multiple ref surface between two limits) then I imagine 99% of the time, the error would be a simple scalar value that could be easily added through a text box/number selector.  The only more complex scenario I could foresee, is someone potentially wanted to specify a spatially variable error based on a polygon mask ... i.e., like the multi-method approach we use for DEMs.  A case in point might be where someone wants to use a water level prediction that they have uncertainty estimates for, but I think such cases would in all likelihood be vanishingly rare.  

2) given (1) above, my gut instinct, is to offer the chance to 'derive' an error surface as a scalar, or REQUIRE them to specify one as an orthogonal raster.  The point being a reference surface HAS to have an error surface.

3) the only area were we could consider being clever (and again, I'm not sure this is worth the effort!) would be when deriving a statistical reference surface (i.e., the mean, min, max etc., on a cell-by-cell basis of a set of rasters).  Here, the error should actually be derived from the errors of the multiple surfaces we are intercomparing ... or we could use some alternative metric, such as the SD of the local elevations as a proxy indicator for uncertainty.  Interested to hear thoughts on that.  Again, this could be an option, with the first approximation being to offer to derive a error surface as a scalar value.

**Comment by philipbaileynar** [comment]
1. @jb10016 please read and comment on issues #67 and #68 that describe how we will handle error surfaces. In essence, I hear and agree that all reference surfaces must have at least one error surface.
1. We can discuss symbology later
1. I've already implemented your suggested simplifications to the wording on the change detection properties from:

![2018-02-13_132942](https://user-images.githubusercontent.com/8645379/36174712-f77c94c2-10c1-11e8-8aaa-e097bafbb655.png)

@jb10016  please close this ticket if you feel I've answered all your comments or they are handled by the new tickets.

**Comment by jb10016** [comment]
Hi Philip,



All looks good – the addition of the derive error surface tools works
smoothly and I like the simple form.



I’ve closed the tickets down.



All the best,

james



| *Professor James Brasington* | Waikato Regional Council Chair of River
Science |

| University of Waikato | Hamilton | New Zealand | Tel: +67 7 858 5046 |

| *Google Scholar* <https://scholar.google.com/citations?user=38_8l8UAAAAJ> |
*ResearcherID* <http://www.researcherid.com/rid/D-3523-2012> |
*ResearchGate* <https://www.researchgate.net/profile/James_Brasington> *|* *UoW
Profile* <http://www.waikato.ac.nz/staff-profiles/people/jbrasing> |



[image: Waik_Word_RGB_H] <https://www.waikato.ac.nz/>







*From:* philipbaileynar [mailto:notifications@github.com]
*Sent:* 14 February 2018 10:31
*To:* Riverscapes/gcd <gcd@noreply.github.com>
*Cc:* James Brasington <james.brasington@waikato.ac.nz>; Mention <
mention@noreply.github.com>
*Subject:* Re: [Riverscapes/gcd] Reference Surface UI (#51)



   1. @jb10016 <https://github.com/jb10016> please read and comment on
   issues #67 <https://github.com/Riverscapes/gcd/issues/67> and #68
   <https://github.com/Riverscapes/gcd/issues/68> that describe how we will
   handle error surfaces. In essence, I hear and agree that all reference
   surfaces must have at least one error surface.
   2. We can discuss symbology later
   3. I've already implemented your suggested simplifications to the
   wording on the change detection properties from:

[image: 2018-02-13_132942]
<https://user-images.githubusercontent.com/8645379/36174712-f77c94c2-10c1-11e8-8aaa-e097bafbb655.png>

@jb10016 <https://github.com/jb10016> please close this ticket if you feel
I've answered all your comments or they are handled by the new tickets.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Riverscapes/gcd/issues/51#issuecomment-365410902>, or mute
the thread
