### ISSUE TITLE
Intra-comparison spreadsheet

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#53]
Implement the ability to generate an intra-comparison spreadsheet two different ways:

1. As part of every budget segregation
1. As part of a user-triggered DoD analysis (i.e. user selects multiple DoDs and then generates the intra-comparison spreadsheet).

Need to discuss format.

**Comment by jb10016** [comment]
@philipbaileynar @MattReimer @joewheaton 

Hi Philip,  I've had a good look through the recent update video, and the progress looks great.  With regards to this specific issues, I think the plan to keep the intercomparison results with the project (in a top level reporting directory) makes a lot of sense.  This keeps all the high level results with the project rather than allowing a user to save it in a separate and undocumented location.  Perhaps my only suggested here is that it might be worth extending this logic ... and creating a 'Report' (or similar name) directory, within which we might in the end have multiple subdirectories that save data that are generated as reports from the GCD project ... e.g., intercomparisons, but possibly also the analyses from cross-sections, long profiles etc.

**Comment by philipbaileynar** [comment]
This is now implemented. Issue #122 has outstanding issues
